apiVersion: v1
# Secret帮你把 Pod 想要访问的加密数据，存放到 Etcd 中。你就可以通过在 Pod 的容器里挂载 Volume 的方式，访问到这些 Secret 里保存的信息了。
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # echo -n 'admin' | base64
  user: YWRtaW4=
   # echo -n '123456' | base64
  pass: MTIzNDU2
