apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "jaeger-memory"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.14
    options:
      log-level: debug
  storage:
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
