apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - name: web
      port: 80
    - name: websecure
      port: 443
    - name: mongo
      port: 27017
    - name: postgres
      port: 5432
    - name: mysql
      port: 3306
    - name: admin
      port: 8080
  selector:
    app: traefik
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      name: traefik
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 1
      containers:
        - image: traefik:2.1.4
          name: traefik-ingress-lb
          ports:
            - name: web
              containerPort: 80
              hostPort: 80 #hostPort方式，将端口暴露到集群节点
            - name: websecure
              containerPort: 443
              hostPort: 443 #hostPort方式，将端口暴露到集群节点
            - name: mongo
              hostPort: 27017
              containerPort: 27017
            - name: postgres
              hostPort: 5432
              containerPort: 5432
            - name: mysql
              hostPort: 3306
              containerPort: 3306
            - name: admin
              containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --configfile=/config/traefik.yaml
          # envFrom:
          # - secretRef:
          #     name: traefik-alidns-secret
          # ALICLOUD_ACCESS_KEY
          # ALICLOUD_SECRET_KEY
          # ALICLOUD_REGION_ID
          volumeMounts:
            - name: acme
              mountPath: /etc/acme
            - name: config
              mountPath: /config
            # - name: certs
            #   mountPath: /certs
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
      volumes:
        - name: config
          configMap:
            name: traefik-config
        - name: acme
          hostPath:
            path: /data/k8s/traefik/acme
      tolerations: #设置容忍所有污点，防止节点被设置污点
        - operator: "Exists"
      nodeSelector: #设置node筛选器，在特定label的节点上启动
        TraefikProxy: "true"
